Repository ovotech/comms-deduplication, pull requests merged in 2023-12, with the labels that each got.

#548 Update logback-classic to 1.4.14
  build.sbt
Labels: ovo-scala-steward, patch-update

#549 Update dynamodb to 2.21.38
  build.sbt
Labels: ovo-scala-steward, patch-update

#552 :wrench: Onboard Scala Steward
  .github/workflows/scala-steward.yml
Labels: kaluza-scala-caretakers

#555 Update sbt to 1.9.8 in master
  project/build.properties
Labels: commit-count:1, library-update, early-semver-patch, semver-spec-patch, version-scheme:early-semver

#557 Update dynamodb to 2.21.46 in master
  build.sbt
Labels: commit-count:1, library-update, early-semver-patch, semver-spec-patch

#553 Update sbt-dynver to 5.0.1 in master
  project/plugins.sbt
Labels: sbt-plugin-update, early-semver-major, semver-spec-major, artifact-migrations, commit-count:1

#554 Update sbt-tpolecat to 0.5.0 in master
  project/plugins.sbt
Labels: sbt-plugin-update, early-semver-major, artifact-migrations, commit-count:1, semver-spec-minor, scalafix-migrations

#556 Update jcl-over-slf4j, slf4j-api to 2.0.9 in master
  build.sbt
Labels: early-semver-major, semver-spec-major, commit-count:1, library-update

#559 Update dynamodb to 2.22.8 in master
  build.sbt
Labels: commit-count:1, semver-spec-minor, library-update, early-semver-minor

#558 Update jcl-over-slf4j, slf4j-api to 2.0.10 in master
  build.sbt
Labels: commit-count:1, library-update, early-semver-patch, semver-spec-patch

#560 Update dynamodb to 2.22.9 in master
  build.sbt
Labels: commit-count:1, library-update, early-semver-patch, semver-spec-patch
